x-service-templates:
  dev: &dev
    build:
      context: .
      dockerfile: build/Dockerfile.api
    networks:
      - rinha
      - payment-processor
    env_file: .env
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "25MB"

services:
  api1:
    <<: *dev
    container_name: api1
    depends_on:
      - postgres
    environment:
      - SERVER=main

  api2:
    <<: *dev
    container_name: api2
    depends_on:
      - postgres
      - api1
  api3:
    <<: *dev
    container_name: api3
    depends_on:
      - postgres
      - api1
  api4:
    <<: *dev
    container_name: api4
    depends_on:
      - postgres
      - api1

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: rinha
      POSTGRES_USER: rinha
      POSTGRES_DB: rinha
    ports:
      - 1010:5432
    volumes:
      - ./configs/postgresql.conf:/etc/postgresql.conf:ro
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "190MB"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha
    depends_on:
      - postgres
      - api1
      - api2
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 60M

networks:
  rinha:
    driver: bridge
  payment-processor:
    external: true